// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGameProcess() {
  return window['go']['main']['App']['CheckGameProcess']();
}

export function CreateBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2, arg3, arg4);
}

export function DetectGamePath() {
  return window['go']['main']['App']['DetectGamePath']();
}

export function GetBackupList(arg1) {
  return window['go']['main']['App']['GetBackupList'](arg1);
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetLocalConfig() {
  return window['go']['main']['App']['GetLocalConfig']();
}

export function GetSharedConfig() {
  return window['go']['main']['App']['GetSharedConfig']();
}

export function RestoreBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2, arg3, arg4);
}

export function SetBackupDirectory(arg1, arg2) {
  return window['go']['main']['App']['SetBackupDirectory'](arg1, arg2);
}

export function UpdateCharacterMapping(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharacterMapping'](arg1, arg2);
}
