// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';

export function CheckGameProcess():Promise<boolean>;

export function CreateBackup(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<void>;

export function DetectGamePath():Promise<string>;

export function GetBackupList(arg1:string):Promise<Array<backup.BackupMeta>>;

export function GetCharacters():Promise<Array<backup.Character>>;

export function GetLocalConfig():Promise<config.LocalConfig>;

export function GetSharedConfig():Promise<config.SharedConfig>;

export function RestoreBackup(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<void>;

export function SetBackupDirectory(arg1:string,arg2:string):Promise<void>;

export function UpdateCharacterMapping(arg1:string,arg2:string):Promise<void>;
